name: Package and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Package the project into a zip file
      - name: Create zip file
        run: |
          zip -r aws-account-identifier.zip . -x '*.git*'

      # Publish the zip file as a GitHub release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: aws-account-identifier.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the packaged browser extension.